"""Low-level C bindings for POSIX termios and TTY system calls."""
from std.sys import CompilationTarget
from std.sys.info import platform_map
from std.ffi import c_int, external_call, get_errno, ErrNo
from std.utils import StaticTuple
from std.memory import MutPointer, ImmPointer


# C types
comptime c_void = NoneType
"""C void type."""
comptime cc_t = UInt8
"""C control character type."""
comptime NCCS = platform_map[macos=20, linux=32]()
"""Number of control characters in `Termios.c_cc`."""
comptime time_t = Int64
"""C time type."""
comptime suseconds_t = Int64
"""C microsecond time type."""
comptime MutExternalPointer[T: AnyType] = MutPointer[T=T, origin=MutUntrackedOrigin, address_space=AddressSpace.GENERIC]
"""A mutable external pointer type.

Parameters:
    T: The pointee type of the pointer.
"""
comptime ImmExternalPointer[T: AnyType] = ImmPointer[T=T, origin=ImmUntrackedOrigin, address_space=AddressSpace.GENERIC]
"""An immutable external pointer type.

Parameters:
    T: The pointee type of the pointer.
"""

comptime tcflag_t = SIMD[platform_map[macos=DType.uint64, linux=DType.uint32](), 1]
"""C terminal mode flag type. `unsigned long` on macOS, `unsigned int` on Linux."""
comptime c_speed_t = SIMD[platform_map[macos=DType.uint64, linux=DType.uint32](), 1]
"""C speed type. `unsigned long` on macOS, `unsigned int` on Linux."""

# Constants
comptime _NSEC_PER_USEC = 1000
comptime _NSEC_PER_MSEC = 1_000_000
comptime _USEC_PER_MSEC = 1000
comptime _MSEC_PER_SEC = 1000
comptime _NSEC_PER_SEC = _NSEC_PER_USEC * _USEC_PER_MSEC * _MSEC_PER_SEC


@fieldwise_init
struct _CTimeSpec(Defaultable, TrivialRegisterPassable, Writable):
    """C Time Struct."""

    var tv_sec: Int  # Seconds
    """Value in seconds."""
    var tv_subsec: Int  # subsecond (nanoseconds on linux and usec on mac)
    """Value in nanoseconds on Linux, and microseconds on Mac."""

    def __init__(out self):
        """Construct a CTimeSpec struct."""
        self.tv_sec = 0
        self.tv_subsec = 0

    def as_nanoseconds(self) -> Int:
        """Calculates the time in nanoseconds.

        Returns:
            The time in nanoseconds.
        """
        comptime if CompilationTarget.is_linux():
            return self.tv_sec * _NSEC_PER_SEC + self.tv_subsec
        else:
            return self.tv_sec * _NSEC_PER_SEC + self.tv_subsec * _NSEC_PER_USEC

    @no_inline
    def write_to(self, mut writer: Some[Writer]):
        """Writes the time in nanoseconds to the writer.

        Args:
            writer: The writer to write to.
        """
        writer.write(self.as_nanoseconds(), "ns")


@fieldwise_init
struct ControlFlag(TrivialRegisterPassable):
    """Control mode flags."""

    var value: tcflag_t
    """Flag value."""
    comptime CREAD = platform_map[macos=Self(2048), linux=Self(128)]()
    """Enable receiver."""
    comptime CLOCAL = platform_map[macos=Self(32768), linux=Self(2048)]()
    """Ignore modem control lines."""
    comptime PARENB = platform_map[macos=Self(4096), linux=Self(256)]()
    """Enable parity generation on output and parity checking on input."""
    comptime CSIZE = platform_map[macos=Self(768), linux=Self(48)]()
    """Character size mask."""
    comptime CS8 = platform_map[macos=Self(768), linux=Self(48)]()
    """8 bits per byte. This is `CSIZE` on both platforms, i.e. every size bit set."""


@fieldwise_init
struct LocalFlag(TrivialRegisterPassable):
    """Local mode flags."""

    var value: tcflag_t
    """Flag value."""
    comptime ICANON = platform_map[macos=Self(256), linux=Self(2)]()
    """Canonical input processing."""
    comptime ECHO = Self(8)
    """Enable echoing of input characters."""
    comptime ECHOE = platform_map[macos=Self(2), linux=Self(16)]()
    """Echo erase character as error-correcting backspace."""
    comptime ECHOK = platform_map[macos=Self(4), linux=Self(32)]()
    """Echo KILL character as a line kill."""
    comptime ECHONL = platform_map[macos=Self(16), linux=Self(64)]()
    """Echo NL after CR on input."""
    comptime ISIG = platform_map[macos=Self(128), linux=Self(1)]()
    """Enable signals generated by INTR, QUIT, SUSP, and DSUSP characters."""
    comptime IEXTEN = platform_map[macos=Self(1024), linux=Self(32768)]()
    """Enable implementation-defined input processing.  This includes the use of the `START` and `STOP` characters for flow control."""
    comptime NOFLSH = platform_map[macos=Self(2147483648), linux=Self(128)]()
    """Disable flushing of output and input queues when generating signals."""
    comptime TOSTOP = platform_map[macos=Self(4194304), linux=Self(256)]()
    """Send SIGTTOU for background process on output."""


@fieldwise_init
struct OutputFlag(TrivialRegisterPassable):
    """Output mode flags. These flags control how `stdout` behaves via output control."""

    var value: tcflag_t
    """Flag value."""
    comptime OPOST = Self(1)
    """Enable implementation-defined output processing."""


@fieldwise_init
struct InputFlag(TrivialRegisterPassable):
    """Input mode flags. These flags control how `stdin` behaves via input control."""

    var value: tcflag_t
    """Flag value."""
    comptime INLCR = Self(64)
    """Map NL to CR on input."""
    comptime IGNCR = Self(128)
    """Ignore CR on input."""
    comptime ICRNL = Self(256)
    """Translate carriage return to newline on input (unless IGNCR is set)."""
    comptime IGNBRK = Self(1)
    """Ignore BREAK condition on input.
    If IGNBRK is set, a BREAK is ignored.  If it is not set
    but BRKINT is set, then a BREAK causes the input and
    output queues to be flushed, and if the terminal is the
    controlling terminal of a foreground process group, it
    will cause a SIGINT to be sent to this foreground process
    group.  When neither IGNBRK nor BRKINT are set, a BREAK
    reads as a null byte ('\\0'), except when PARMRK is set, in
    which case it reads as the sequence \\377 \\0 \\0."""
    comptime BRKINT = Self(2)
    """Signal interrupt on BREAK."""
    comptime IGNPAR = Self(4)
    """Ignore framing errors and parity errors.
    If this bit is set, input bytes with parity or framing
    errors are marked when passed to the program.  This bit is
    meaningful only when INPCK is set and IGNPAR is not set.
    The way erroneous bytes are marked is with two preceding
    bytes, \\377 and \\0.  Thus, the program actually reads
    three bytes for one erroneous byte received from the
    terminal.  If a valid byte has the value \\377, and ISTRIP
    (see below) is not set, the program might confuse it with
    the prefix that marks a parity error.  Therefore, a valid
    byte \\377 is passed to the program as two bytes, \\377
    \\377, in this case."""

    # If neither IGNPAR nor PARMRK is set, read a character with
    # a parity error or framing error as \0.

    comptime PARMRK = Self(8)
    """Mark parity and framing errors."""
    comptime INPCK = Self(16)
    """Enable input parity checking."""
    comptime ISTRIP = Self(32)
    """Strip off eighth bit."""

    comptime IXON = platform_map[macos=Self(512), linux=Self(1024)]()
    """Enable XON/XOFF flow control on output."""
    comptime IXANY = Self(2048)
    """(XSI) Typing any character will restart stopped output. (The default is to allow just the START character to restart output)."""
    comptime IXOFF = platform_map[macos=Self(1024), linux=Self(4096)]()
    """Enable XON/XOFF flow control on input."""

    # comptime IMAXBEL
    #         (not in POSIX) Ring bell when input queue is full.  Linux
    #         does not implement this bit, and acts as if it is always
    #         set.

    # comptime IUTF8 (since Linux 2.6.4)
    #         (not in POSIX) Input is UTF8; this allows character-erase
    #         to be correctly performed in cooked mode.


@fieldwise_init
struct SpecialCharacter(TrivialRegisterPassable):
    """Special Character indexes for control characters."""

    var value: cc_t
    """Special control characters."""

    comptime VEOF = platform_map[macos=Self(0), linux=Self(4)]()
    """Signal End-Of-Input `Ctrl-D`."""
    comptime VEOL = platform_map[macos=Self(1), linux=Self(11)]()
    """Signal End-Of-Line `Disabled`."""
    comptime VERASE = platform_map[macos=Self(3), linux=Self(2)]()
    """Delete previous character `Backspace`."""
    comptime VINTR = platform_map[macos=Self(8), linux=Self(0)]()
    """Generate SIGINT `Ctrl-C`."""
    comptime VKILL = platform_map[macos=Self(5), linux=Self(3)]()
    """Erase current line `Ctrl-U`."""
    comptime VMIN = platform_map[macos=Self(16), linux=Self(6)]()
    """The MIN value `1`."""
    comptime VQUIT = platform_map[macos=Self(9), linux=Self(1)]()
    """Generate SIGQUIT `Ctrl-\\`."""
    comptime VSTART = platform_map[macos=Self(12), linux=Self(8)]()
    """Resume output `Ctrl-Q`."""
    comptime VSTOP = platform_map[macos=Self(13), linux=Self(9)]()
    """Suspend output `Ctrl-S`."""
    comptime VSUSP = Self(10)
    """Suspend program `Ctrl-Z`."""
    comptime VTIME = platform_map[macos=Self(17), linux=Self(5)]()
    """The TIME value `0`."""


@fieldwise_init
struct Termios(TrivialRegisterPassable, Writable):
    """Termios libc.

    #### Notes:
    The field order and widths mirror the platform's C `struct termios` exactly,
    because this is passed by pointer to `tcgetattr`/`tcsetattr`. Linux's glibc
    struct carries a `cc_t c_line` line-discipline byte between `c_lflag` and
    `c_cc` which macOS does not have; `_c_line` reserves it, and is zero-width
    on macOS so the layout stays correct on both.
    """

    comptime _CONTROL_CHARACTER_WIDTH = NCCS
    comptime _LINE_DISCIPLINE_WIDTH = platform_map[macos=0, linux=1]()

    var c_iflag: tcflag_t
    """Input mode flags."""
    var c_oflag: tcflag_t
    """Output mode flags."""
    var c_cflag: tcflag_t
    """Control mode flags."""
    var c_lflag: tcflag_t
    """Local mode flags."""
    var _c_line: StaticTuple[cc_t, Self._LINE_DISCIPLINE_WIDTH]
    """Line discipline. Linux only; zero-width padding on macOS."""
    var c_cc: StaticTuple[cc_t, Self._CONTROL_CHARACTER_WIDTH]
    """Special control characters."""
    var c_ispeed: c_speed_t
    """Input baudrate."""
    var c_ospeed: c_speed_t
    """Output baudrate."""

    def __init__(out self):
        """Initializes the Termios struct with default values."""
        self.c_cc = StaticTuple[cc_t, Self._CONTROL_CHARACTER_WIDTH]()
        comptime for n in range(Self._CONTROL_CHARACTER_WIDTH):
            self.c_cc[n] = 0

        self._c_line = StaticTuple[cc_t, Self._LINE_DISCIPLINE_WIDTH]()
        comptime for n in range(Self._LINE_DISCIPLINE_WIDTH):
            self._c_line[n] = 0

        self.c_cflag = 0
        self.c_lflag = 0
        self.c_iflag = 0
        self.c_oflag = 0
        self.c_ispeed = 0
        self.c_ospeed = 0


def tcgetattr[origin: MutOrigin, //](fd: c_int, termios_p: MutPointer[Termios, origin]) -> c_int:
    """Libc POSIX `tcgetattr` function.

    Get the parameters associated with the terminal referred to by the file descriptor `fd`.

    Parameters:
        origin: The origin of the Termios pointer.

    Args:
        fd: File descriptor.
        termios_p: Termios struct.

    Returns:
        The result of the operation, typically 0 on success or -1 in case of failure.

    #### C Function:
    ```c
    int tcgetattr(int fd, struct Termios *termios_p);
    ```

    #### Notes:
    Reference: https://man7.org/linux/man-pages/man3/tcgetattr.3.html.
    """
    return external_call["tcgetattr", c_int, c_int, MutPointer[Termios, origin]](fd, termios_p)


def tcsetattr[
    origin: ImmOrigin, //
](fd: c_int, optional_actions: c_int, termios_p: ImmPointer[Termios, origin]) -> c_int:
    """Libc POSIX `tcsetattr` function.

    Set the parameters associated with the terminal referred to by the file descriptor `fd`.

    Parameters:
        origin: The origin of the Termios pointer.

    Args:
        fd: File descriptor.
        optional_actions: Optional actions.
        termios_p: Termios struct.

    Returns:
        The result of the operation, typically 0 on success or -1 in case of failure.

    #### C Function:
    ```c
    int tcsetattr(int fd, int optional_actions, const struct Termios *termios_p);
    ```

    #### Notes:
    Reference: https://man7.org/linux/man-pages/man3/tcsetattr.3.html.
    """
    return external_call["tcsetattr", c_int, c_int, c_int, ImmPointer[Termios, origin]](fd, optional_actions, termios_p)


def tcsendbreak(fd: c_int, duration: c_int) -> c_int:
    """Libc POSIX `tcsendbreak` function.

    Send a break on the terminal referred to by the file descriptor `fd`.

    Args:
        fd: File descriptor.
        duration: Duration.

    Returns:
        The result of the operation, typically 0 on success or -1 in case of failure.

    #### C Function:
    ```c
    int tcsendbreak(int fd, int duration);
    ```

    #### Notes:
    Reference: https://man7.org/linux/man-pages/man3/tcsendbreak.3.html.
    """
    return external_call["tcsendbreak", c_int, c_int, c_int](fd, duration)


def tcdrain(fd: c_int) -> c_int:
    """Libc POSIX `tcdrain` function.

    Drain the output buffer of the terminal referred to by the file descriptor `fd`.

    Args:
        fd: File descriptor.

    Returns:
        The result of the operation, typically 0 on success or -1 in case of failure.

    #### C Function:
    ```c
    int tcdrain(int fd);
    ```

    #### Notes:
    Reference: https://man7.org/linux/man-pages/man3/tcdrain.3.html.
    """
    return external_call["tcdrain", c_int, c_int](fd)


def tcflush(fd: c_int, queue_selector: c_int) -> c_int:
    """Libc POSIX `tcflush` function.

    Flush the data transmitted or received on the terminal referred to by the file descriptor `fd`.

    Args:
        fd: File descriptor.
        queue_selector: Queue selector.

    Returns:
        The result of the operation, typically 0 on success or -1 in case of failure.

    #### C Function:
    ```c
    int tcflush(int fd, int queue_selector);
    ```

    #### Notes:
    Reference: https://man7.org/linux/man-pages/man3/tcflush.3.html.
    """
    return external_call["tcflush", c_int, c_int, c_int](fd, queue_selector)


def tcflow(fd: c_int, action: c_int) -> c_int:
    """Libc POSIX `tcflow` function.

    Suspend or resume transmission on the terminal referred to by the file descriptor `fd`.

    Args:
        fd: File descriptor.
        action: Action.

    Returns:
        The result of the operation, typically 0 on success or -1 on failure.

    #### C Function:
    ```c
    int tcflow(int fd, int action);
    ```

    #### Notes:
    Reference: https://man7.org/linux/man-pages/man3/tcflow.3.html.
    """
    return external_call["tcflow", c_int, c_int, c_int](fd, action)


def cfmakeraw[origin: MutOrigin, //](termios_p: MutPointer[Termios, origin]):
    """Libc POSIX `cfmakeraw` function.

    Set the terminal attributes to raw mode.

    Parameters:
        origin: The origin of the Termios pointer.

    Args:
        termios_p: Reference to a Termios struct.

    #### C Function:
    ```c
    void cfmakeraw(struct Termios *termios_p);
    ```

    #### Notes:
    Reference: https://man7.org/linux/man-pages/man3/cfmakeraw.3.html.
    """
    external_call["cfmakeraw", c_void, MutPointer[Termios, origin]](termios_p)


# @fieldwise_init
# @register_passable("trivial")
# struct winsize():
#     var ws_row: UInt8      # Number of rows, in characters */
#     var ws_col: UInt8      # Number of columns, in characters */
#     var ws_xpixel: UInt8   # Width, in pixels */
#     var ws_ypixel: UInt8   # Height, in pixels */

#     def __init__(out self):
#         self.ws_row = 0
#         self.ws_col = 0
#         self.ws_xpixel = 0
#         self.ws_ypixel = 0


# def tcgetwinsize(fd: c_int, winsize_p: Pointer[winsize]) -> c_int:
#     """Libc POSIX `tcgetwinsize` function
#     Reference: https://man.netbsd.org/tcgetwinsize.3
#     def signature: int tcgetwinsize(int fd, struct winsize *gws).

#     Args:
#         fd: File descriptor.
#         winsize_p: Pointer to a winsize struct.
#     """
#     return external_call["tcgetwinsize", c_int, c_int, Pointer[winsize]](fd, winsize_p)


# def tcsetwinsize(fd: c_int, winsize_p: Pointer[winsize]) -> c_int:
#     """Libc POSIX `tcgetwinsize` function
#     Reference: https://man.netbsd.org/tcsetwinsize.3
#     def signature: int tcsetwinsize(int fd, const struct winsize *sws).

#     Args:
#         fd: File descriptor.
#         winsize_p: Pointer to a winsize struct.
#     """
#     return external_call["tcsetwinsize", c_int, c_int, Pointer[winsize]](fd, winsize_p)
